packaging:
  add:
    - target/osiam

links:
  - ${database}

ports:
  - 8280

healthChecks:
  pings:
    - url: http://localhost:8280/manager/text/list
      timeout: 80000
      pattern: osiam:running

tag: ${project.artifactId}_tomcat-${database}
